# Используем базовый образ
FROM ubuntu:latest

# Установим необходимые зависимости или команды
RUN echo "Hello, Docker!"

# Укажем команду, которая будет выполняться при запуске контейнера
CMD ["echo", "Hello from the Docker container!"]

# Output is "Hello grom the Docker container"